name: Go package

on: 
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: Build
        run: cd windows && GOOS=windows go build -v -ldflags="-s -w"
      - uses: crazy-max/ghaction-upx@v3
        with:
          version: latest
          files: |
            windows/NoWhatsNew.exe
          args: -fq --lzma --best
      - uses: svenstaro/upload-release-action@v2
        with:
          asset_name: NoWhatsNew-${{ github.event.release.tag_name }}.exe
          file: windows/NoWhatsNew.exe
